// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/articulos" | "/articulos/show/[id]" | "/caja" | "/clientes" | "/club" | "/compras" | "/configuracion" | "/configuracion/administradores" | "/configuracion/club" | "/configuracion/permisos-rol" | "/dashboard" | "/dashboard/secretaria" | "/fidelizacion" | "/historial" | "/login" | "/marketing-center" | "/nomina" | "/proveedores" | "/register" | "/ventas"
type AppRouteHandlerRoutes = "/api/ai/generate" | "/api/ai/ingest" | "/api/articulos" | "/api/auth/create-user" | "/api/auth/delete-user" | "/api/club" | "/api/club/canjes" | "/api/club/puntos" | "/api/club/recomendaciones" | "/api/club/referido" | "/api/club/verificar" | "/api/club/voucher" | "/api/configuracion/club" | "/api/configuracion/club/recompensas" | "/api/configuracion/club/recompensas/[id]" | "/api/create-user" | "/api/cron/recordatorios-pago" | "/api/historial" | "/api/marketing-center/promociones" | "/api/marketing-center/push-campaign" | "/api/movimientos/delete" | "/api/og-image" | "/api/pagos" | "/api/perfiles" | "/api/push/subscribe" | "/api/push/unsubscribe" | "/api/whatsapp/send" | "/auth/callback" | "/og.png"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/ai/generate": {}
  "/api/ai/ingest": {}
  "/api/articulos": {}
  "/api/auth/create-user": {}
  "/api/auth/delete-user": {}
  "/api/club": {}
  "/api/club/canjes": {}
  "/api/club/puntos": {}
  "/api/club/recomendaciones": {}
  "/api/club/referido": {}
  "/api/club/verificar": {}
  "/api/club/voucher": {}
  "/api/configuracion/club": {}
  "/api/configuracion/club/recompensas": {}
  "/api/configuracion/club/recompensas/[id]": { "id": string; }
  "/api/create-user": {}
  "/api/cron/recordatorios-pago": {}
  "/api/historial": {}
  "/api/marketing-center/promociones": {}
  "/api/marketing-center/push-campaign": {}
  "/api/movimientos/delete": {}
  "/api/og-image": {}
  "/api/pagos": {}
  "/api/perfiles": {}
  "/api/push/subscribe": {}
  "/api/push/unsubscribe": {}
  "/api/whatsapp/send": {}
  "/articulos": {}
  "/articulos/show/[id]": { "id": string; }
  "/auth/callback": {}
  "/caja": {}
  "/clientes": {}
  "/club": {}
  "/compras": {}
  "/configuracion": {}
  "/configuracion/administradores": {}
  "/configuracion/club": {}
  "/configuracion/permisos-rol": {}
  "/dashboard": {}
  "/dashboard/secretaria": {}
  "/fidelizacion": {}
  "/historial": {}
  "/login": {}
  "/marketing-center": {}
  "/nomina": {}
  "/og.png": {}
  "/proveedores": {}
  "/register": {}
  "/ventas": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
