// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/articulos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/articulos">> = Specific
  const handler = {} as typeof import("../../src/app/articulos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/articulos/show/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/articulos/show/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/articulos/show/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/caja/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/caja">> = Specific
  const handler = {} as typeof import("../../src/app/caja/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/clientes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/clientes">> = Specific
  const handler = {} as typeof import("../../src/app/clientes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/club/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/club">> = Specific
  const handler = {} as typeof import("../../src/app/club/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/compras/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/compras">> = Specific
  const handler = {} as typeof import("../../src/app/compras/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/configuracion/administradores/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/configuracion/administradores">> = Specific
  const handler = {} as typeof import("../../src/app/configuracion/administradores/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/configuracion/club/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/configuracion/club">> = Specific
  const handler = {} as typeof import("../../src/app/configuracion/club/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/configuracion/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/configuracion">> = Specific
  const handler = {} as typeof import("../../src/app/configuracion/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/configuracion/permisos-rol/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/configuracion/permisos-rol">> = Specific
  const handler = {} as typeof import("../../src/app/configuracion/permisos-rol/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/secretaria/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/secretaria">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/secretaria/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/fidelizacion/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/fidelizacion">> = Specific
  const handler = {} as typeof import("../../src/app/fidelizacion/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/historial/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/historial">> = Specific
  const handler = {} as typeof import("../../src/app/historial/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/marketing-center/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/marketing-center">> = Specific
  const handler = {} as typeof import("../../src/app/marketing-center/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/nomina/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/nomina">> = Specific
  const handler = {} as typeof import("../../src/app/nomina/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/proveedores/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/proveedores">> = Specific
  const handler = {} as typeof import("../../src/app/proveedores/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../src/app/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/ventas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ventas">> = Specific
  const handler = {} as typeof import("../../src/app/ventas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/generate">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai/ingest/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/ingest">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai/ingest/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/articulos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/articulos">> = Specific
  const handler = {} as typeof import("../../src/app/api/articulos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/create-user/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/create-user">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/create-user/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/delete-user/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/delete-user">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/delete-user/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/club/canjes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/club/canjes">> = Specific
  const handler = {} as typeof import("../../src/app/api/club/canjes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/club/puntos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/club/puntos">> = Specific
  const handler = {} as typeof import("../../src/app/api/club/puntos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/club/referido/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/club/referido">> = Specific
  const handler = {} as typeof import("../../src/app/api/club/referido/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/club/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/club">> = Specific
  const handler = {} as typeof import("../../src/app/api/club/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/club/voucher/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/club/voucher">> = Specific
  const handler = {} as typeof import("../../src/app/api/club/voucher/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/configuracion/club/recompensas/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/configuracion/club/recompensas/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/configuracion/club/recompensas/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/configuracion/club/recompensas/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/configuracion/club/recompensas">> = Specific
  const handler = {} as typeof import("../../src/app/api/configuracion/club/recompensas/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/configuracion/club/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/configuracion/club">> = Specific
  const handler = {} as typeof import("../../src/app/api/configuracion/club/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/create-user/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/create-user">> = Specific
  const handler = {} as typeof import("../../src/app/api/create-user/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/recordatorios-pago/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/recordatorios-pago">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/recordatorios-pago/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/historial/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/historial">> = Specific
  const handler = {} as typeof import("../../src/app/api/historial/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/movimientos/delete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/movimientos/delete">> = Specific
  const handler = {} as typeof import("../../src/app/api/movimientos/delete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/og-image/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/og-image">> = Specific
  const handler = {} as typeof import("../../src/app/api/og-image/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/pagos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pagos">> = Specific
  const handler = {} as typeof import("../../src/app/api/pagos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/perfiles/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/perfiles">> = Specific
  const handler = {} as typeof import("../../src/app/api/perfiles/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/whatsapp/send/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/whatsapp/send">> = Specific
  const handler = {} as typeof import("../../src/app/api/whatsapp/send/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/callback">> = Specific
  const handler = {} as typeof import("../../src/app/auth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/og.png/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/og.png">> = Specific
  const handler = {} as typeof import("../../src/app/og.png/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
